### PR TITLE
feat: display audio file icon when no thumbnailUrl and encodingFormat is audio

### PR DESCRIPTION
**Pull request by shc261392**
## Changed
- Display audio file svg when  no `thumbnailUrl` available and `encodingFormat` is audio

### CODE REVIEW

**Comment by olgahaha** [comment]
in the description, did you mean audio file **svg**?

**Comment by shc261392** [comment]
> in the description, did you mean audio file **svg**?

Yes, it's a typo. Updated

**Review by olgahaha — APPROVED** [review]

**Comment by olgahaha** [comment]
just to confirm, do you want to use the gray SVG instead of the gray music icon?

**Comment by shc261392** [comment]
> just to confirm, do you want to use the gray SVG instead of the gray music icon?

@olgahaha Which gray music icon you are talking about? SVG code is preferred over icons from remote url as it should be faster to load in browser.

**Review by olgahaha — APPROVED** [review]

**Pull request merged**
